# Generated by Django 5.2.8 on 2025-12-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewritehistory',
            name='language',
            field=models.CharField(default='english', max_length=50),
        ),
    ]
